DROP TABLE IF EXISTS groups;

CREATE TABLE groups (
    id SERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    time_period INTEGER NOT NULL,
    story TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gul_user_id INTEGER,
    grun_user_id INTEGER,
    vermel_user_id INTEGER,
    bezrechu_user_id INTEGER,
    sagol_user_id INTEGER,
    gul_role VARCHAR(64),
    grun_role VARCHAR(64),
    vermel_role VARCHAR(64),
    bezrechu_role VARCHAR(64),
    sagol_role VARCHAR(64),
    gul_character VARCHAR(64),
    grun_character VARCHAR(64),
    vermel_character VARCHAR(64),
    bezrechu_character VARCHAR(64),
    sagol_character VARCHAR(64),
    gul_text TEXT,
    grun_text TEXT,
    vermel_text TEXT,
    bezrechu_text TEXT,
    sagol_text TEXT
);
